run-tests needs a source of APKs to function
The test runs on jenkins.debian.net were failing because they
specified a dir that did not exist.

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -99,6 +99,10 @@ if [ -z "$1" ]; then
 else
     APKDIR=$1
 fi
+if [ ! -d "$APKDIR" ]; then
+    echo "ERROR: '$APKDIR' does not exist!"
+    exit 1
+fi
 
 if [ -z $WORKSPACE ]; then
     WORKSPACE=`dirname $(pwd)`
