tests: allow running with only androguard, no Android SDK

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -72,9 +72,14 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 fi
 
 if [ -z "$ANDROID_HOME" ]; then
-    echo "ANDROID_HOME must be set with the path to the Android SDK, i.e.: "
-    echo "  export ANDROID_HOME=/opt/android-sdk"
-    exit 1
+    if python3 -c "import androguard"; then
+        echo "ANDROID_HOME is not set, using androguard"
+    else
+        echo "ERROR: ANDROID_HOME is not set, androguard is not available!"
+        exit 1
+    fi
+else
+    echo "Using ANDROID_HOME=$ANDROID_HOME"
 fi
 
 if [ -d tests ]; then
