run-tests: exit with error if no test APKs are found
There must be at least one APK available for this test suite to work, for
example, this test:

grep -F '<application id=' repo/index.xml

This can't be easily implemented using an env vir beccause the while
loop is running in a pipe, so a different process.
copy_apks_into_repo is used with throwaway tmp dirs, so the stamp file
should work well.

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -24,8 +24,13 @@ copy_apks_into_repo() {
             echo "$f --> repo/$apk"
             ln "$f" $1/repo/$apk || \
                 rsync -axv "$f" $1/repo/$apk # rsync if hard link is not possible
+	    touch $1/.found-apks
         fi
     done
+    if [ ! -e $1/.found-apks ]; then
+	echo "ERROR: The dir APKDIR must have APKs in it! $APKDIR does not."
+	exit 1
+    fi
     set -x
 }
 
